use get started
evmos/docs pull request #7
Opened 2023-02-07 11:29 UTC by danburck

- draft intro
- docs(use): add getting started seections without using technical terms
- docs(use): move technical sections to developer introduction
- docs(use): fix typos

2023-02-07 11:44 UTC, danburck commented
@masterfung There are conflicts with `main` because I decided to create a one-pager to get started instead of a whole folder. Can we keep it like this?

2023-02-09 19:59 UTC, masterfung commented on docs/develop/index.md
> +Ethereum, while at the same time, benefit from Tendermint’s PoS implementation. Also, because it is
I would spell out PoS here

2023-02-09 20:00 UTC, masterfung commented on docs/develop/index.md
> +Evmos allows for running vanilla Ethereum as a [Cosmos](https://cosmos.network/)
not sure about the use of `vanilla` here to describe Ethereum

2023-02-09 20:04 UTC, masterfung requested changes
a few small changes requested.

2023-02-13 16:39 UTC, masterfung approved these changes

2023-02-13 16:39 UTC, merged